#%RAML 1.0
title: languages Translators API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: languages Translators API
    content: This documents the API calls that can be made to query and manage languages translators

types:
  languageTranslator: !include languageTranslator.json
  languageTranslators: !include languageTranslators.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/languageTranslators:
  type:
    collection:
      exampleCollection: !include examples/languageTranslators.json
      exampleItem: !include examples/languageTranslator.json
      schemaCollection: languageTranslators
      schemaItem: languageTranslator
  get:
    is: [
      searchable: { description: "with valid searchable fields", example: "localeCode=ar"},
      pageable
    ]
    description: Return a list of languages translators
  post:
    description: Create a new language translator
    is: [validate]
  delete:
    description: "Delete all language translator"
    is: [language]
    responses:
      204:
        description: "All language translator delete"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  /{languageTranslatorId}:
    description: Pass the id for the language translators
    type:
      collection-item:
        exampleItem: !include examples/languageTranslator.json
        schema: languageTranslator
    put:
        description: Update a language translators
        is: [validate]
        responses:
          422:
            description: "Validation error"
            body:
              application/json:
                type: errors






