#%RAML 1.0
title: languages API
version: v3.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: languages API
    content: This documents the API calls that can be made to query and manage languages

types:
  language: !include language.json
  languages: !include languages.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/languages:
  type:
    collection:
      exampleCollection: !include examples/languages.json
      exampleItem: !include examples/language.json
      schemaCollection: languages
      schemaItem: language
  get:
    is: [
      searchable: { description: "with valid searchable fields", example: "name=Arabic"},
      pageable
    ]
    description: Return a list of languages
  post:
    description: Create a new language
    is: [validate]
    responses:
      422:
        description: "Validation error"
        body:
          application/json:
            type: errors
  delete:
    description: "Delete all languages"
    is: [language]
    responses:
      204:
        description: "All languages delete"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  /{languageId}:
    description: Pass the id for the language
    type:
      collection-item:
        exampleItem: !include examples/language.json
        schema: language
    put:
        description: Update a language
        is: [validate]
        responses:
          422:
            description: "Validation error"
            body:
              application/json:
                type: errors
